spring.mongodb.uri=mongodb://localhost:27017/workshop_mongo

# Enable auto-index creation for MongoDB repositories (necessary for unique constraints to work)
spring.data.mongodb.auto-index-creation=true